# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.17
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/takumakanari/cronv
    steps:
      - checkout
      - run: go test -v ./... -bench .
      - run: mkdir -p /go/src/github.com/takumakanari/cronv/cmd
      - run: go build -o cmd/cronv cronv/main.go
      - store_artifacts:
          path: cmd/cronv
