name: Test & Build

on: 
  push:
    branches: [ master ]
  pull_request:

env:
  GO_VERSION: 1.17

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Test
        run: go test -v ./... -bench .
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go build -o /tmp/cronv cronv/main.go
